version: 2.1

jobs:
  build-aria2:
    parameters:
      dockerImage:
        description: Docker image to be used to build
        type: string
      archType:
        description: Architecture type for which the build is executed
        type: string
      artifactName:
        description: Name of the final artifact generated
        type: string
    docker:
      - image: << parameters.dockerImage >>
    steps:
      - checkout
      - run:
          name: aria2 << parameters.archType >> build
          command: "bash build_aria2_<< parameters.archType >>.sh"
      - store_artifacts:
          path: /tmp/final_build/<< parameters.artifactName >>
          destination: << parameters.artifactName >>
      - run:
          name: Publishing aria2 build to cloudsmith repo
          command: "bash cloudsmith_artifact_uploader.sh << parameters.artifactName >>"

workflows:
  build-aria2-workflow:
    jobs:
      - build-aria2: # Build for amd64 arch
          dockerImage: ubuntu:22.04
          archType: amd64
          artifactName: aria2c_amd64
      - build-aria2: # Build for amd32 arch
          dockerImage: i386/ubuntu:18.04
          archType: amd32
          artifactName: aria2c_amd32
      - build-aria2: # Build for mingw64 arch
          dockerImage: ubuntu:22.04
          archType: mingw64
          artifactName: aria2c_mingw64.exe
      - build-aria2: # Build for mingw32 arch
          dockerImage: i386/ubuntu:18.04
          archType: mingw32
          artifactName: aria2c_mingw32.exe
