# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-aria2-amd64:
    docker:
      - image: ubuntu:22.04
    steps:
      - checkout
      - run:
          name: "Build aria2 amd64"
          command: "bash build_aria2_amd64.sh"
      - store_artifacts:
          path: /home/circleci/final_build/aria2c_amd64
          destination: aria2c_amd64
  build-aria2-amd32:
    docker:
      - image: i386/ubuntu:18.04
    steps:
      - checkout
      - run:
          name: "Build aria2 amd32"
          command: "bash build_aria2_amd32.sh"
      - store_artifacts:
          path: /home/circleci/final_build/aria2c_amd32
          destination: aria2c_amd32

workflows:
  build-aria2-workflow:
    jobs:
      - build-aria2-amd64
      - build-aria2-amd32

